ALTER TABLE technicians ADD COLUMN IF NOT EXISTS rank VARCHAR(10) DEFAULT 'bronze';
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS rank_points INTEGER DEFAULT 0;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS certifications_count INTEGER DEFAULT 0;
ALTER TABLE service_ratings ADD COLUMN IF NOT EXISTS rated_by VARCHAR(20) DEFAULT 'client';
ALTER TABLE service_ratings ADD COLUMN IF NOT EXISTS rater_id VARCHAR(50) DEFAULT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS client_confirmed_at TIMESTAMP DEFAULT NULL;
DROP INDEX IF EXISTS ix_service_ratings_service_id;
